### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by jebbdomingo** [foliolabs/foliokit#47]
Sending of email using WordPress's `wp_mail()` isn't working.

Note: Not pretty sure if this belongs here or in vagrant box repo.

**Comment by johanjanssens** [comment]
@jebbdomingo The box captures emails using mailcatcher, but you need to configure it correctly. Probably you haven't configured your wordpress instance to send mail to mailcatcher? 

See: https://www.joomlatools.com/developer/tools/vagrant/faq#how-to-test-e-mails

**Comment by jebbdomingo** [comment]
Thanks @johanjanssens, an smtp plugin for WP needs to be installed to set it up correctly.
